const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("codexDesktop", {
  getState: () => ipcRenderer.invoke("app:get-state"),
  newThread: () => ipcRenderer.invoke("thread:new"),
  resumeThread: (threadId) => ipcRenderer.invoke("thread:resume", threadId),
  refreshThreadTokenUsage: (threadId) => ipcRenderer.invoke("thread:refresh-token-usage", threadId),
  archiveThread: (threadId) => ipcRenderer.invoke("thread:archive", threadId),
  rollbackThread: (payload) => ipcRenderer.invoke("thread:rollback", payload),
  startTurn: (payload) => ipcRenderer.invoke("turn:start", payload),
  startReview: (payload) => ipcRenderer.invoke("review:start", payload),
  refreshGit: () => ipcRenderer.invoke("git:refresh"),
  login: (payload) => ipcRenderer.invoke("account:login", payload),
  cancelLogin: (loginId) => ipcRenderer.invoke("account:cancel-login", loginId),
  logout: () => ipcRenderer.invoke("account:logout"),
  readRateLimits: () => ipcRenderer.invoke("account:rate-limits"),
  readConfig: () => ipcRenderer.invoke("config:read"),
  writeConfigValue: (payload) => ipcRenderer.invoke("config:value-write", payload),
  openConfig: () => ipcRenderer.invoke("config:open-user"),
  updateUiConfig: (patch) => ipcRenderer.invoke("ui-config:update", patch),
  copyText: (text) => ipcRenderer.invoke("clipboard:write-text", text),
  readFileLink: (href) => ipcRenderer.invoke("file:read-link", href),
  openExternal: (url) => ipcRenderer.invoke("shell:open-external", url),
  openLicenses: () => ipcRenderer.invoke("licenses:open"),
  updateMemoryPreferences: (payload) => ipcRenderer.invoke("memory:preferences-update", payload),
  resetMemories: () => ipcRenderer.invoke("memory:reset"),
  chooseWorkspace: () => ipcRenderer.invoke("workspace:choose"),
  openWorkspace: (workspace) => ipcRenderer.invoke("workspace:open", workspace),
  respondToApproval: (payload) => ipcRenderer.invoke("approval:respond", payload),
  windowMinimize: () => ipcRenderer.invoke("window:minimize"),
  windowMaximize: () => ipcRenderer.invoke("window:maximize"),
  windowClose: () => ipcRenderer.invoke("window:close"),
  onServerStatus: (callback) => ipcRenderer.on("codex:server-status", (_event, payload) => callback(payload)),
  onServerLog: (callback) => ipcRenderer.on("codex:server-log", (_event, payload) => callback(payload)),
  onEvent: (callback) => ipcRenderer.on("codex:event", (_event, payload) => callback(payload)),
  onApprovalRequest: (callback) => ipcRenderer.on("codex:approval-request", (_event, payload) => callback(payload)),
});
